baseURL = 'https://hyounggyu.com/'
title = 'My Dev Notes'
theme = ["PaperMod"]

DefaultContentLanguage = 'ko'
Paginate = 5
# SectionPagesMenu = 'main'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[permalinks]
  posts = '/:year/:month/:day/:slug/'

[minify]
disableXML = true

[languages]

[languages.ko]
title = 'My Dev Notes'
weight = 1
contentDir = 'content/ko'
languageName = ":kr:"
languageAltTitle = "Korean"

  [languages.ko.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

  [[languages.ko.menu.main]]
  name = "Archive"
  url = "archives/"
  weight = 10

  [[languages.ko.menu.main]]
  name = "Search"
  url = "search/"
  weight = 20

  [[languages.ko.menu.main]]
  name = "Tags"
  url = "tags/"
  weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = ""
author = "Kim Hyounggyu"
defaultTheme = "auto"
ShowShareButtons = false
ShowReadingTime = false
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true
# images = [ "papermod-cover.png" ]

  [params.homeInfoParams]
  Title = "My Dev Notes"
  Content = """몇 가지"""

  [[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/hyounggyu"

  [[params.socialIcons]]
  name = "RSS"
  url = "index.xml"

  [params.editPost]
  URL = "https://github.com/hyounggyu/hyounggyu.github.io/tree/src/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true