baseURL = 'https://hyounggyu.com/'
title = 'My Dev Notes'
theme = ["PaperMod"]

DefaultContentLanguage = 'ko'
Paginate = 5
# SectionPagesMenu = 'main'
staticDir = ['static']

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
# buildDrafts = true
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[permalinks]
posts = '/:year/:month/:day/:slug/'

[minify]
disableXML = true

[languages]

[languages.ko]
title = 'My Dev Notes'
weight = 1
contentDir = 'content/ko'
disabled = false
languageCode = 'ko-KR'
languageDirection = 'ltr'
languageName = 'Korean'

[languages.ko.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.ko.menu.main]]
name = "Archive"
url = "archives/"
weight = 10

[[languages.ko.menu.main]]
name = "Search"
url = "search/"
weight = 20

[[languages.ko.menu.main]]
name = "Tags"
url = "tags/"
weight = 30

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
description = "My Personal Dev Notes"
author = "KIM, HYOUNGGYU"
defaultTheme = "auto"
ShowReadingTime = false
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
displayFullLangName = true
DateFormat = "2006-01-02"
# images = [ "papermod-cover.png" ]

[params.homeInfoParams]
Title = "My Dev Notes"
Content = """Hi"""

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/hyounggyu"

[[params.socialIcons]]
name = "RSS"
url = "index.xml"

[params.editPost]
URL = "https://github.com/hyounggyu/hyounggyu.github.io/tree/src/content"
Text = "Suggest Changes"
appendFilePath = true

[params.assets]
disableHLJS = false

[markup]

[markup.goldmark.renderer]
unsafe = true

# [markup.highlight]
# codeFences = true
# guessSyntax = true
# lineNos = true
# style = "monokai"

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
